version: "3.8"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: ${image_tag:-nocobase/nocobase:0.7.4-alpha.7}
    networks:
      - nocobase
    depends_on:
      mysql:
          condition: service_healthy
    environment:
      - DB_DIALECT=mysql
      - DB_HOST=mysql
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=nocobase
      - LOCAL_STORAGE_BASE_URL=http://localhost:13000/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: nocobase
      MYSQL_USER: nocobase
      MYSQL_PASSWORD: nocobase
      MYSQL_ROOT_PASSWORD: nocobase
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      timeout: 5s
      interval: 10s
      retries: 3

    networks:
      - nocobase
