name: manual-deploy-pr
# environment: manual-deploy-pr secrets:
# registry_url
# image_name
# registry_username
# registry_password
# deploy_host
# deploy_host_username
# deploy_host_password
env:
  docker_compose_file: ./workflow/docker-compose.yml
on:
  workflow_dispatch:
    inputs:
      deploy_pr_type:
        description: 'decision image name '
        required: true
        default: 'feat'
        type: choice
        options:
          - feat
          - bug

jobs:
  deploy:
    strategy:
      matrix:
        node_version: [ '14' ]
    runs-on: ubuntu-latest
    services:
      verdaccio: # used to build docker image
        image: verdaccio/verdaccio
        ports:
          - 4873:4873
    environment:
      name: manual-deploy-pr  # Settings -> Environments ->
      # url: https://github.com
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: yarn install and build
        run: |
          yarn config set registry https://registry.npmjs.org/
          yarn install
          yarn build

      - name: install expect
        run: |
          sudo apt-get update
          sudo apt-get -y install expect
      - name: adduser and login verdaccio npm registry
        run: |
          set timeout 10
          spawn npm adduser --registry http://localhost:4873
          expect "Username:"
          send "test\n"
          expect "Password:"
          send "123456\n"
          expect "Email: (this IS public)"
          send "test@mail.com\n"
          spawn npm login --registry http://localhost:4873
          expect "Username:"
          send "test\n"
          expect "Password:"
          send "123456\n"
          expect "Email: (this IS public)"
          send "test@mail.com\n"
        shell: expect {0}

      - name: publish to verdaccio npm registry
        id: publish_verdaccio
        run: |
          yarn version:alpha -y
          git config user.email "test@mail.com"
          git config user.name "test"
          git add .
          git commit -m "chore(versions): test publish packages xxx"
          yarn release:force --registry http://localhost:4873

      - name: build and publish docker image
        run: |
          docker login --username=${{ secrets.registry_username }} --password=${{ secrets.registry_password }} ${{ secrets.registry_url }}
          docker image build --network host -t ${{ secrets.registry_url }}/${{ secrets.image_name }}:${{ inputs.deploy_pr_type }}-${{ github.sha }} ./workflow
          docker push ${{ secrets.registry_url }}/${{ secrets.image_name }}:${{ inputs.deploy_pr_type }}-${{ github.sha }}


      - name: copy deploy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.deploy_host }}
          username: ${{ secrets.deploy_host_username }}
          password: ${{ secrets.deploy_host_password }}
          source: ${{ env.docker_compose_file }}
          target: "/deploy"

      - name: ssh deploy
        uses: appleboy/ssh-action@master
        env:
          image_tag: ${{ secrets.registry_url }}/${{ secrets.image_name }}:${{ inputs.deploy_pr_type }}-${{ github.sha }}
        with:
          host: ${{ secrets.deploy_host }}
          username: ${{ secrets.deploy_host_username }}
          password: ${{ secrets.deploy_host_password }}
          script: |
            docker login --username=${{ secrets.registry_username }} --password=${{ secrets.registry_password }} ${{ secrets.registry_url }}
            docker pull ${{ env.image_tag }}
            export image_tag=${{ env.image_tag }}
            cd /deploy
            docker-compose -f ${{ env.docker_compose_file }} up -d
