name: test event

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '**'
      
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/

      - name: 'test skip shell false'
        run: |
          echo '::echo::on'
          echo 'pr status ?'
          echo ${{ github.event_type }}
          echo ${{ github.event.number }}
          echo ${{ github.event}}
          echo ${{ github}}

      - name: text message
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              hahahah
              from github action test
              repository: ${{ github.repository }}
              committer: ${{ github.actor }}
              compare: ${{ github.event.compare }}
              job status: ${{ job.status }}
              access url: https://www.baidu.com
              备注: 请及时更新任务系统的任务状态：https://tasks.nocobase.com/